# Generated by Django 4.2.30 on 2026-09-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='wedding_qr/'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
