# Generated by Django 4.2.30 on 2026-09-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_wedding_qr_code_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='face_descripter',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
