# Generated by Django 4.2.30 on 2026-09-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_photo_face_descripter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='face_descripter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
