# Generated by Django 4.2.30 on 2026-09-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_photo_face_descripter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='face_descripter',
            new_name='face_descriptor',
        ),
    ]
