# Generated by Django 4.2.30 on 2026-09-22 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_googledriveaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='drive_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weddings', to='accounts.googledriveaccounts'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
