# Generated by Django 4.2.30 on 2026-09-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_wedding_drive_account_wedding_drive_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
