# Generated by Django 4.2.30 on 2026-10-04 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_guest_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingDriveConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drive_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wedding_connecitons', to='accounts.googledriveaccounts')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_connectoins', to='accounts.wedding')),
            ],
            options={
                'unique_together': {('wedding', 'drive_account', 'folder_id')},
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='drive_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='accounts.weddingdriveconnection'),
        ),
    ]
