# Generated by Django 4.2.30 on 2026-10-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_weddingdriveconnection_photo_drive_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='qr_code_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
